add_newline = false
command_timeout = 100

format = "$directory$git_branch$git_status$cmd_duration$character "

[directory]
format = "[$path]($style) "
style = "bold"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
format = "($branch) "
style = "dimmed"

[git_status]
format = "[$all_status]($style) "
style = "green"

[cmd_duration]
format = "[$duration]($style) "
style = "dimmed"
min_time = 2000

[character]
success_symbol = ">"
error_symbol = "x"
vicmd_symbol = "<"
format = "$symbol "

[package]
disabled = true
[rust]
disabled = true
[python]
disabled = true
[c]
disabled = true
[nodejs]
disabled = true
[golang]
disabled = true
