#!/bin/sh
sed -i 's:"/home/thierry/.colours/.*":"/home/thierry/.colours/dark":' /home/thierry/.Xresources
sed -i 's: <):):' /home/thierry/.fluxbox/menu-colours
sed -i 's:dark):dark <):' /home/thierry/.fluxbox/menu-colours
xrdb -merge /home/thierry/.Xresources
exit
