#!/bin/sh
sed -i 's:"/home/thierry/.colours/.*":"/home/thierry/.colours/lich":' /home/thierry/.Xresources
sed -i 's: <):):' /home/thierry/.fluxbox/menu-colours
sed -i 's:lich):lich <):' /home/thierry/.fluxbox/menu-colours
xrdb -merge /home/thierry/.Xresources
exit
