#!/bin/sh
sed -i 's:"/home/thierry/.colours/.*":"/home/thierry/.colours/old":' /home/thierry/.Xresources
sed -i 's: <):):' /home/thierry/.fluxbox/menu-colours
sed -i 's:old):old <):' /home/thierry/.fluxbox/menu-colours
xrdb -merge /home/thierry/.Xresources
exit
