#!/bin/sh
sed -i 's:"/home/thierry/.colours/.*":"/home/thierry/.colours/raised":' /home/thierry/.Xresources
sed -i 's: <):):' /home/thierry/.fluxbox/menu-colours
sed -i 's:raised):raised <):' /home/thierry/.fluxbox/menu-colours
xrdb -merge /home/thierry/.Xresources
exit
