#!/bin/sh
sed -i 's:"/home/thierry/.colours/.*":"/home/thierry/.colours/soft":' /home/thierry/.Xresources
sed -i 's: <):):' /home/thierry/.fluxbox/menu-colours
sed -i 's:soft):soft <):' /home/thierry/.fluxbox/menu-colours
xrdb -merge /home/thierry/.Xresources
exit
