"       .__                                      _____
"___  __|__|  _____        ____   ____    ____ _/ ____\
"\  \/ /|  | /     \     _/ ___\ /  _ \  /    \\   __\
" \   / |  ||  Y Y  \    \  \___(  <_> )|   |  \|  |
"  \_/  |__||__|_|  /     \___  >\____/ |___|  /|__|
"                 \/          \/             \/ by hzr
"

call plug#begin('~/.vim/plugged')
   Plug 'morhetz/gruvbox'
   Plug 'junegunn/fzf'
   Plug 'junegunn/fzf.vim'
   Plug 'tpope/vim-commentary'
   Plug 'tpope/vim-surround'
   Plug 'itchyny/lightline.vim'
   Plug 'mengelbrecht/lightline-bufferline'

"  [off] 
"  Plug 'mg979/vim-visual-multi'
"  Plug 'vim-pandoc/vim-pandoc', { 'for': ['markdown', 'pandoc'] }
"  Plug 'lervag/vimtex'
"  Plug 'ap/vim-css-color'
"  Plug 'luochen1990/rainbow'
"  Plug 'tpope/vim-fugitive'
"  Plug 'mengelbrecht/lightline-bufferline'
"  Plug 'honza/vim-snippets'
"  Plug 'c9s/perlomni.vim'
"  Plug 'osyo-manga/vim-over'
"  Plug 'vim-scripts/sudo.vim'
"  Plug 'itchyny/lightline.vim'
"  Plug 'neoclide/coc.nvim', {'branch': 'release'}
"  Plug 'preservim/nerdtree'
"  Plug 'terryma/vim-multiple-cursors'
"  Plug 'airblade/vim-gitgutter'
"  Plug 'jiangmiao/auto-pairs'
"  Plug 'preservim/tagbar'
"  Plug 'dag/vim-fish'
"  Plug 'vim-perl/vim-perl'
"  Plug 'sheerun/vim-polyglot'
"  Plug 'w0rp/ale'
"  Plug 'mhinz/vim-startify'
"  Plug 'mhinz/vim-signify', { 'branch': 'legacy' }
"  Plug 'ryanoasis/vim-devicons'
"  Plug 'Stoozy/vimcord'
"  Plug 'mopp/autodirmake.vim'
call plug#end()

set encoding=utf-8
set number
set showcmd
set wildmenu
set hidden
set noerrorbells belloff=all
set ttimeout ttimeoutlen=10
set synmaxcol=200

if has('termguicolors') | set termguicolors | endif
set background=dark
silent! colorscheme gruvbox

set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

set ignorecase
set smartcase
set incsearch
set hlsearch

set wrap
set linebreak
" if has('clipboard') | set clipboard=unnamedplus | endif
if executable('wl-copy') && !empty($WAYLAND_DISPLAY)
  autocmd TextYankPost * if v:event.operator ==# 'y' | call system('wl-copy', @0) | endif
endif

set laststatus=2
set noshowmode

set showtabline=2
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ 'active': {
      \   'left':  [ ['mode', 'paste'], ['readonly', 'filename', 'modified'] ],
      \   'right': [ ['lineinfo'], ['percent'], ['filetype'] ]
      \ },
      \ 'inactive': {
      \   'left':  [ ['filename'] ],
      \   'right': [ ['lineinfo'] ]
      \ }
      \ }

let g:lightline#bufferline#show_number = 2
let g:lightline#bufferline#modified = ' +'
let g:lightline#bufferline#unnamed = '[No Name]'

let g:lightline.component_expand = { 'buffers': 'lightline#bufferline#buffers' }
let g:lightline.component_type   = { 'buffers': 'tabsel' }
let g:lightline.tabline = {
      \ 'left':  [ ['buffers'] ],
      \ 'right': [ ['close'] ]
      \ }


let g:netrw_banner = 0
let g:netrw_winsize = 25

let mapleader = ' '
nnoremap <leader>e :Lexplore<CR>
nnoremap <Tab> :bnext<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" muscular training moves h j k l
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
