function __dialog_complete
    # Special
    complete -c dialog -l create-rc -d "Gerar arquivo de config padrão"

    # Common options
    complete -c dialog -l ascii-lines -d "Usa linhas ASCII"
    complete -c dialog -l aspect -r -d "Define proporção da caixa"
    complete -c dialog -l backtitle -r -d "Título no topo"
    complete -c dialog -l beep -d "Bip ao finalizar"
    complete -c dialog -l beep-after -d "Bip após fechar"
    complete -c dialog -l begin -r -d "Posição inicial Y X"
    complete -c dialog -l cancel-label -r -d "Texto do botão Cancelar"
    complete -c dialog -l clear -d "Limpa a tela ao sair"
    complete -c dialog -l color-mode -r -d "Máscara de cores"
    complete -c dialog -l colors -d "Habilita cores"
    complete -c dialog -l column-separator -r -d "Separador de coluna"
    complete -c dialog -l cr-wrap -d "Quebra linhas CR"
    complete -c dialog -l cursor-off-label -d "Label quando cursor off"
    complete -c dialog -l date-format -r -d "Formato de data"
    complete -c dialog -l default-button -r -d "Botão padrão"
    complete -c dialog -l default-item -r -d "Item padrão"
    complete -c dialog -l defaultno -d "Foco no botão Não"
    complete -c dialog -l erase-on-exit -d "Apaga tela ao sair"
    complete -c dialog -l exit-label -r -d "Texto do botão Exit"
    complete -c dialog -l extra-button -d "Ativa botão Extra"
    complete -c dialog -l extra-label -r -d "Texto do botão Extra"
    complete -c dialog -l help-button -d "Ativa botão Help"
    complete -c dialog -l help-label -r -d "Texto do botão Help"
    complete -c dialog -l help-status -d "Retorna status de help"
    complete -c dialog -l help-tags -d "Ajuda com tags"
    complete -c dialog -l hfile -r -d "Arquivo de help"
    complete -c dialog -l hline -r -d "Texto de header"
    complete -c dialog -l ignore -d "Ignora eventos"
    complete -c dialog -l input-fd -r -d "FD para entrada"
    complete -c dialog -l insecure -d "Input não oculto"
    complete -c dialog -l item-help -d "Ajuda por item"
    complete -c dialog -l keep-tite -d "Mantém modo alternate"
    complete -c dialog -l keep-window -d "Mantém janela aberta"
    complete -c dialog -l last-key -d "Mostra última tecla"
    complete -c dialog -l max-input -r -d "Tamanho máx do input"
    complete -c dialog -l no-cancel -d "Remove botão Cancel"
    complete -c dialog -l no-collapse -d "Sem colapso de parágrafos"
    complete -c dialog -l no-hot-list -d "Desativa hotlist"
    complete -c dialog -l no-items -d "Sem itens"
    complete -c dialog -l no-kill -d "Não fecha em sinais"
    complete -c dialog -l no-label -r -d "Texto do botão No"
    complete -c dialog -l no-lines -d "Sem bordas"
    complete -c dialog -l no-mouse -d "Desativa mouse"
    complete -c dialog -l no-nl-expand -d "Sem expansão de \\n"
    complete -c dialog -l no-ok -d "Remove botão OK"
    complete -c dialog -l no-shadow -d "Sem sombras"
    complete -c dialog -l no-tags -d "Sem tags"
    complete -c dialog -l ok-label -r -d "Texto do botão OK"
    complete -c dialog -l output-fd -r -d "FD para saída"
    complete -c dialog -l output-separator -r -d "Separador de output"
    complete -c dialog -l print-maxsize -d "Imprime tamanho máx"
    complete -c dialog -l print-size -d "Imprime tamanho"
    complete -c dialog -l print-text-only -r -d "Imprime texto"
    complete -c dialog -l print-text-size -r -d "Imprime tam. texto"
    complete -c dialog -l print-version -d "Mostra versão"
    complete -c dialog -l quoted -d "Saída entre aspas"
    complete -c dialog -l reorder -d "Reordena itens"
    complete -c dialog -l scrollbar -d "Ativa scrollbar"
    complete -c dialog -l separate-output -d "Saída por linha"
    complete -c dialog -l separate-widget -r -d "Widget separador"
    complete -c dialog -l single-quoted -d "Saída com aspas simples"
    complete -c dialog -l size-err -d "Erro ao calcular tamanho"
    complete -c dialog -l sleep -r -d "Dormir N segundos"
    complete -c dialog -l stderr -d "Output no stderr"
    complete -c dialog -l stdout -d "Output no stdout"
    complete -c dialog -l tab-correct -d "Correção de tabs"
    complete -c dialog -l tab-len -r -d "Tamanho do tab"
    complete -c dialog -l time-format -r -d "Formato de hora"
    complete -c dialog -l timeout -r -d "Timeout"
    complete -c dialog -l title -r -d "Título da caixa"
    complete -c dialog -l trace -r -d "Log de trace"
    complete -c dialog -l trim -d "Remove espaços extras"
    complete -c dialog -l version -d "Mostrar versão"
    complete -c dialog -l visit-items -d "Permite visitar itens"
    complete -c dialog -l week-start -r -d "Dia da semana inicial"
    complete -c dialog -l yes-label -r -d "Texto do botão Yes"

    # Box widgets
    complete -c dialog -l buildlist -d "Lista com seleção múltipla"
    complete -c dialog -l calendar -d "Calendário"
    complete -c dialog -l checklist -d "Checklist"
    complete -c dialog -l dselect -d "Selecionar diretório"
    complete -c dialog -l editbox -d "Editor de texto"
    complete -c dialog -l form -d "Formulário"
    complete -c dialog -l fselect -d "Selecionar arquivo"
    complete -c dialog -l gauge -d "Gauge/progresso"
    complete -c dialog -l infobox -d "Caixa informativa"
    complete -c dialog -l inputbox -d "Input de texto"
    complete -c dialog -l inputmenu -d "Menu de input"
    complete -c dialog -l menu -d "Menu"
    complete -c dialog -l mixedform -d "Formulário misto"
    complete -c dialog -l mixedgauge -d "Gauge misto"
    complete -c dialog -l msgbox -d "Mensagem"
    complete -c dialog -l passwordbox -d "Input de senha"
    complete -c dialog -l passwordform -d "Formulário de senha"
    complete -c dialog -l pause -d "Pausa com contador"
    complete -c dialog -l prgbox -d "Executa comando"
    complete -c dialog -l programbox -d "Mostra saída de programa"
    complete -c dialog -l progressbox -d "Caixa de progresso"
    complete -c dialog -l radiolist -d "Lista de rádio"
    complete -c dialog -l rangebox -d "Range numérico"
    complete -c dialog -l tailbox -d "Tail de arquivo"
    complete -c dialog -l tailboxbg -d "Tail em background"
    complete -c dialog -l textbox -d "Mostrar arquivo de texto"
    complete -c dialog -l timebox -d "Seleção de hora"
    complete -c dialog -l treeview -d "Árvore"
    complete -c dialog -l yesno -d "Caixa Yes/No"
end

__dialog_complete

