function __lynx_complete
    complete -c lynx -f

	complete -c lynx -s - -d "Read options and arguments from stdin"

	complete -c lynx -l accept_all_cookies -d "Accept cookies without prompting"
	complete -c lynx -l cookies -d "Toggle cookie handling"
	complete -c lynx -l cookie_file -d "Cookie file to read"
	complete -c lynx -l cookie_save_file -d "Cookie file to store"
	complete -c lynx -l auth -d "Authentication id:pw"
	complete -c lynx -l pauth -d "Proxy authentication id:pw"
	complete -c lynx -l force_secure -d "Force secure flag on SSL cookies"

	complete -c lynx -l anonymous -d "Enable anonymous mode"
	complete -c lynx -l restrictions -d "Set restrictions"
	complete -c lynx -l validate -d "Validate-only mode"
	complete -c lynx -l assume_charset -d "Assume charset"
	complete -c lynx -l assume_local_charset -d "Assume charset for local files"
	complete -c lynx -l assume_unrec_charset -d "Fallback charset"
	complete -c lynx -l display_charset -d "Charset for terminal output"
	complete -c lynx -l html5_charsets -d "Toggle HTML5 charset replacements"
	complete -c lynx -l raw -d "Toggle 8-bit translations or CJK mode"

	complete -c lynx -l cfg -d "Specify lynx.cfg"
	complete -c lynx -l lss -d "Specify lynx.lss"
	complete -c lynx -l term -d "Set terminal type"

	complete -c lynx -l session -d "Resume/save session"
	complete -c lynx -l sessionin -d "Resume session from file"
	complete -c lynx -l sessionout -d "Save session to file"
	complete -c lynx -l noinit -d "Do not load init script"

	complete -c lynx -l book -d "Use bookmark page as startfile"
	complete -c lynx -l base -d "Add BASE tag on source dumps"
	complete -c lynx -l child -d "Exit on left-arrow in startfile (no save)"
	complete -c lynx -l child_relaxed -d "Exit on left-arrow (save allowed)"
	complete -c lynx -l connect_timeout -d "Connection timeout"
	complete -c lynx -l read_timeout -d "Read timeout"
	complete -c lynx -l partial -d "Partial page display"
	complete -c lynx -l partial_thres -d "Lines before repaint when partial"
	complete -c lynx -l traversal -d "Traverse http links"
	complete -c lynx -l localhost -d "Disable remote hosts"

	complete -c lynx -l center -d "Center-align tables"
	complete -c lynx -l collapse_br_tags -d "Collapse <br> tags"
	complete -c lynx -l dont_wrap_pre -d "Don't wrap <pre> in dumps"
	complete -c lynx -l minimal -d "Minimal comment parsing"
	complete -c lynx -l historical -d "Old comment terminator behavior"
	complete -c lynx -l force_html -d "Force interpret as HTML"
	complete -c lynx -l link -d "Starting link number for crawl"
	complete -c lynx -l list_decoded -d "Decode URLs in dumps"
	complete -c lynx -l list_inline -d "Show links inline in dumps"
	complete -c lynx -l listonly -d "Show only list of links"
	complete -c lynx -l nolist -d "Disable link lists"
	complete -c lynx -l nonumbers -d "Disable link numbering"
	complete -c lynx -l number_links -d "Force numbering of links"
	complete -c lynx -l number_fields -d "Number form fields"
	complete -c lynx -l scrollbar -d "Show scrollbar"
	complete -c lynx -l scrollbar_arrow -d "Show arrows on scrollbar"
	complete -c lynx -l image_links -d "Create links for images"
	complete -c lynx -l pseudo_inlines -d "Pseudo alt text for inline images"
	complete -c lynx -l justify -d "Justify text"
	complete -c lynx -l tagsoup -d "Use TagSoup parser"
	complete -c lynx -l xhtml_parsing -d "Enable XHTML parsing"
	complete -c lynx -l use_mouse -d "Enable mouse support"

	complete -c lynx -l default_colors -d "Use terminal default FG/BG"
	complete -c lynx -l nocolor -d "Disable color support"
	complete -c lynx -l nobold -d "Disable bold"
	complete -c lynx -l noreverse -d "Disable reverse video"
	complete -c lynx -l nounderline -d "Disable underline"
	complete -c lynx -l underline_links -d "Underline links"
	complete -c lynx -l underscore -d "Use _underline_ formatting"
	complete -c lynx -l width -d "Width of dumps"
	complete -c lynx -l with_backspaces -d "Emit backspaces in dump"

	complete -c lynx -l dump -d "Dump first file to stdout"
	complete -c lynx -l source -d "Dump source of first file"
	complete -c lynx -l mime_header -d "Include MIME headers"
	complete -c lynx -l base -d "Add BASE tag to output"
	complete -c lynx -l stderr -d "Write warnings to stderr when dumping"

	complete -c lynx -l core -d "Force core dumps"
	complete -c lynx -l cmd_log -d "Log keystrokes"
	complete -c lynx -l cmd_script -d "Read keystrokes from file"
	complete -c lynx -l debug_partial -d "Incremental rendering debug"
	complete -c lynx -l error_file -d "Write HTTP code here"
	complete -c lynx -l tlog -d "Trace log"
	complete -c lynx -l trace -d "Enable trace mode"
	complete -c lynx -l trace_mask -d "Set trace mask"
	complete -c lynx -l stack_dump -d "Disable cleanup handler"

	complete -c lynx -l ftp -d "Disable ftp"
	complete -c lynx -l telnet -d "Disable telnet"
	complete -c lynx -l rlogin -d "Disable rlogin"
	complete -c lynx -l socks5_proxy -d "Use SOCKS5 proxy"
	complete -c lynx -l passive_ftp -d "Use passive FTP"

	complete -c lynx -l head -d "Send HEAD request"
	complete -c lynx -l from -d "Toggle From: header"
	complete -c lynx -l nofileferer -d "Disable Referer for file://"
	complete -c lynx -l noreferer -d "Disable Referer"
	complete -c lynx -l noredir -d "Disable redirection"
	complete -c lynx -l reload -d "Flush proxy cache"

	complete -c lynx -l useragent -d "Set alternate User-Agent"

	complete -c lynx -l get_data -d "Read GET form data from stdin"
	complete -c lynx -l post_data -d "Read POST data from stdin"
	complete -c lynx -l resubmit_posts -d "Force POST resubmission"

	complete -c lynx -l editor -d "Specify editor"
	complete -c lynx -l emacskeys -d "Use Emacs-like keys"
	complete -c lynx -l vikeys -d "Use vi-like keys"
	complete -c lynx -l enable_scrollback -d "Comm program scrollback keys"
	complete -c lynx -l popup -d "Popup or radio-style selects"
	complete -c lynx -l tna -d "Textfields need activation"

	complete -c lynx -l homepage -d "Set homepage URL"
	complete -c lynx -l index -d "Default index file"

	complete -c lynx -l noprint -d "Disable print functions"
	complete -c lynx -l print -d "Enable print functions"

	complete -c lynx -l nozap -d "Disable 'z' key checks"
	complete -c lynx -l nofileferer -d "Disable Referer for file URLs"
	complete -c lynx -l nostatus -d "Disable status messages"
	complete -c lynx -l notitle -d "Disable page title"
	complete -c lynx -l short_url -d "Shorten long URLs in status"
	complete -c lynx -l unique_urls -d "Unique URLs for dumps"

	complete -c lynx -l help -d "Show help message"
	complete -c lynx -l version -d "Show version"
end


__lynx_complete
