complete -c sl -s a -d "An accident is occurring. People cry for help!"
complete -c sl -s c -d "C51 appears instead of D51."
complete -c sl -s d -d "Disco mode."
complete -c sl -s e -d "Escape(ctrlc or ctrld)"
complete -c sl -s F -d "It flies like the galaxy express 999"
complete -c sl -s l -d "little version"
complete -c sl -s v -d "Print version"
complete -c sl -s w -d "Faster"
complete -c sl -s G -d "It's French like Oscar."
complete -c sl -s 0 -d "Number of vagons [0 or.. infinite]"
