complete -c trans -f

complete -c trans -l version    -s V  -d "Print version and exit"
complete -c trans -l help       -s H  -d "Print help message and exit"
complete -c trans -l man        -s M  -d "Show man page and exit"
complete -c trans -l reference  -s T  -d "Show language reference table (endonyms)"
complete -c trans -l reference-english -s R -d "Show language reference table (English)"
complete -c trans -l list-engines -s S -d "List translation engines"
complete -c trans -l list-languages -d "List all languages (endonyms)"
complete -c trans -l list-languages-english -d "List languages (English names)"
complete -c trans -l list-codes -d "List language codes"
complete -c trans -l list-all -d "List all languages and codes"
complete -c trans -l linguist -s L -d "Show detailed info of languages"
complete -c trans -l upgrade  -s U -d "Check for program upgrade"

complete -c trans -l engine  -s e -d "Select translation engine"

complete -c trans -l verbose -d "Verbose mode"
complete -c trans -l brief   -s b -d "Brief translation"
complete -c trans -l dictionary -s d -d "Dictionary mode"
complete -c trans -l identify -d "Identify language"
complete -c trans -l show-original -d "Show original text"
complete -c trans -l show-original-phonetics -d "Show phonetics of original"
complete -c trans -l show-translation -d "Show translated text"
complete -c trans -l show-translation-phonetics -d "Show phonetics of translation"
complete -c trans -l show-prompt-message -d "Show prompt message"
complete -c trans -l show-languages -d "Show source/target languages"
complete -c trans -l show-original-dictionary -d "Show original dictionary entry"
complete -c trans -l show-dictionary -d "Show dictionary entry"
complete -c trans -l show-alternatives -d "Show alternative translations"
complete -c trans -l width -s w -d "Set display width"
complete -c trans -l indent -d "Set indentation size"
complete -c trans -l theme -d "Specify theme"
complete -c trans -l no-theme -d "Disable theme"
complete -c trans -l no-ansi -d "Disable ANSI colors"
complete -c trans -l no-autocorrect -d "Disable autocorrect"
complete -c trans -l no-bidi -d "Disable bidi processing"
complete -c trans -l bidi -d "Force bidi processing"
complete -c trans -l no-warn -d "Suppress warnings"
complete -c trans -l dump -d "Print raw API response"

complete -c trans -l play -s p -d "Play translation audio"
complete -c trans -l speak -d "Play original audio"
complete -c trans -l narrator -s n -d "Select narrator voice"
complete -c trans -l player -d "Select audio player"
complete -c trans -l no-play -d "Disable audio playback"
complete -c trans -l no-translate -d "Don't translate on -speak"
complete -c trans -l download-audio -d "Download audio file"
complete -c trans -l download-audio-as -d "Download audio as filename"

complete -c trans -l view -s v -d "View translation in pager"
complete -c trans -l pager -d "Select pager program"
complete -c trans -l no-view -d "Disable pager"
complete -c trans -l browser -d "Select web browser"
complete -c trans -l no-browser -d "Disable browser"

complete -c trans -l proxy -s x -d "Use HTTP proxy"
complete -c trans -l user-agent -s u -d "Set User-Agent string"
complete -c trans -l ipv4 -s 4 -d "Use IPv4 only"
complete -c trans -l ipv6 -s 6 -d "Use IPv6 only"

complete -c trans -l interactive -s I -d "Start interactive shell"
complete -c trans -l emacs -s E -d "Start Emacs frontend"
complete -c trans -l no-rlwrap -d "Don't use rlwrap"

complete -c trans -l input -s i -d "Read input from file"
complete -c trans -l output -s o -d "Write output to file"

complete -c trans -l host -s hl -d "Set interface language"
complete -c trans -l source -s s -d "Set source language"
complete -c trans -l target -s t -d "Set target language"

complete -c trans -l join-sentence -s j -d "Join all args into one sentence"

complete -c trans -l no-init -d "Do not load init script"

