HISTFILE="$HOME/.zsh/.history"
if [ -d "$HISTFILE" ]; then
    continue
else
    touch "$HISTFILE"
    chmod 600 "$HISTFILE"
fi

HISTSIZE="10000"
SAVEHIST="10000"

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt EXTENDED_HISTORY

[[ -o interactive ]] || return

setopt extendedglob
setopt globstarshort

zmodload zsh/net/tcp

autoload -U colors && colors
autoload -Uz vcs_info

zstyle ':vcs_info:git:*' formats '%F{green}%r%f%F{white}:%f%F{white}(%f%F{magenta}%b%f%F{white})%f%F{blue} %c%f%F{red} %u%f%F{yellow}%a%f '
zstyle ':vcs_info:git:*' enable git
zstyle ':vcs_info:git:*' actionformats '(%b|%a)'
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' branchformat '%b (%i)'


setopt PROMPT_SUBST

typeset -g CMD_START_TIME
typeset -g CMD_DURATION
typeset -g CMD_COLOR

preexec()
{
    CMD_START_TIME=$EPOCHREALTIME
}

precmd()
{
    if [[ -n $CMD_START_TIME ]]; then
        local end_time=$EPOCHREALTIME
        local duration=$(echo "$end_time - $CMD_START_TIME" | bc -l)
        local int_duration=${duration%.*}

    if ((int_duration >= 86400)); then
        CMD_COLOR="%F{magenta}"
    elif ((int_duration >= 43200)); then
        CMD_COLOR="%F{red}"
    elif ((int_duration >= 3600)); then
        CMD_COLOR="%F{green}"
    elif ((int_duration >= 1)); then
        CMD_COLOR="%F{white}"
    fi


        if (( $(echo "$duration > 1" | bc -l) )); then
            CMD_DURATION=$(printf "%2.fs " "$duration")
        else
            CMD_DURATION=""
        fi

        unset CMD_START_TIME
    fi

    vcs_info
}

exit_code()
{
    ec=$?
    [[ ec -ne 0 ]] && echo "%B%F{red}(${ec})%f%b "
}

PS1='%F{white}[%f%F{cyan}%n%f%F{white}@%f%F{yellow}%m%f%F{blue} %2~%f%F{white}]%f $(exit_code)${vcs_info_msg_0_}%f${CMD_COLOR}${CMD_DURATION}%f%# '

if command -v zoxide >/dev/null; then
    eval "$(zoxide init zsh)"
fi

if [[ -z "$TMUX" ]]; then
    tmux attach -t main 2>/dev/null || tmux new -s main
fi

export MANLANG=pt_BR.UTF-8
export EDITOR=vim
export VISUAL=vim
export PAGER=less

if [[ -f $HOME/.local/bin ]]; then
    mkdir -p "$HOME/.local/bin"
fi

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME/.local/bin:$HOME/.cargo/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.local/share/gem/ruby/3.4.0/bin:$PATH"

autoload -Uz compinit
compinit

bindkey -v
export KEYTIMEOUT=1

if [[ ! -f ~/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    mkdir -p ~/.local/share/zinit
    git clone https://github.com/zdharma-continuum/zinit.git \
        ~/.local/share/zinit/zinit.git
fi

if [ ! -d ".zsh/completion" ]; then
    mkdir -p .zsh_completion 2>/dev/null
    echo "# this completion is a test please ignore :3" | tee $HOME/.zsh/completion/example &>/dev/null
else
    source $HOME/.zsh/completion/* 2>/dev/null
fi

source ~/.local/share/zinit/zinit.git/zinit.zsh

zinit light lukechilds/zsh-nvm
zinit light junegunn/fzf
zinit light hlissner/zsh-autopair
zinit light wfxr/forgit
zinit light momo-lab/zsh-abbrev-alias
zinit light ael-code/zsh-colored-man-pages
zinit light zsh-users/zsh-history-substring-search
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

if [[ -f /usr/bin/eza ]]; then
    alias ls='eza --color=always'
else
    alias ls='ls --color=always'
fi

if [ -f /usr/bin/grep ]; then
    alias grep='grep --color'
fi
if [[ -f /usr/bin/bat ]]; then
    alias bcat='bat --style=plain --paging=never --theme=gruvbox-dark'
fi

if [ -f /usr/bin/vim ]; then
    alias vi='vim'
fi

if [[ -f /usr/bin/{bc,git,zsh,eza,bat,tmux,vim} ]]; then
    if [[ -f /usr/bin/pacman ]]; then
        yes | sudo pacman -S <<EOF
    $(cat $HOME/.zsh/int/packages) 
EOF
    fi
fi
