# ::::::::: .::::::.   ::   .: :::::::..     .,-:::::
# '`````;;;;;;`    `  ,;;   ;;,;;;;``;;;;  ,;;;'````'
#     .n[[''[==/[[[[,,[[[,,,[[[ [[[,/[[['  [[[
#   ,$$P"    '''    $"$$$"""$$$ $$$$$$c    $$$ by hzr
# ,888bo,_  88b    dP 888   "88o888b "88bo,`88bo,__,o,
#  `""*UMM   "YMmMY"  MMM    YMMMMMM   "W"   "YUMMMMMP"

[[ -z SWAYSOCK ]] && [ "$(tty)" = "/dev/tty1" ] && {
    /usr/bin/start-session
}

HISTFILE="$HOME/.zsh/.history"
if [ -d "$HISTFILE" ]; then
    continue
else
    touch "$HISTFILE"
    chmod 600 "$HISTFILE"
fi

HISTSIZE="1000000"
SAVEHIST="1000000"

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE
setopt EXTENDED_HISTORY
HISTCONTROL=ignorespace

[[ -o interactive ]] || return

setopt extendedglob
setopt globstarshort

zmodload zsh/net/tcp

autoload -U colors && colors
autoload -Uz vcs_info

zstyle ':vcs_info:git:*' formats '%F{green}%r%f%F{white}:%f%F{white}(%f%F{magenta}%b%f%F{white})%f%F{blue}%c%f%F{red} %u%f%F{yellow}%a%f'
zstyle ':vcs_info:git:*' enable git
zstyle ':vcs_info:git:*' actionformats '(%b|%a)'
zstyle ':vcs_info:git:*' check-for-changes false
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' branchformat '%b (%i)'

setopt PROMPT_SUBST

typeset -g CMD_START_TIME
typeset -g CMD_DURATION
typeset -g CMD_COLOR

PS1='%F{white}[%n%f%F{white}@%f%F{green}%m%f%F{white}]%f:%F{blue}%~ %f${vcs_info_msg_0_}%f${CMD_COLOR}${CMD_DURATION}%f%F{white}%#%f '
PS2='%(?.%F{green}.%F{red})%_%f%F{white} ...%f '

## use in scripts -w-
# PS3=' \e[31m?> \e[0m'
# PS4=' \e[32m+\e[0m \e[31m${FUNCNAME[0]}\e[0m:\e[90m$(basename "$0"):\e[1m$LINENO:\e[0m] '
##

# if command -v zoxide >/dev/null; then
#     eval "$(zoxide init zsh)"
# fi

if [[ -z "$TMUX" ]]; then
    tmux attach -t main 2>/dev/null || tmux new -s main
fi

export MANLANG=pt_BR.UTF-8
export EDITOR=vim
export VISUAL=vim
export PAGER=less
export LESS='-R -M -i -J -w -z-4'
export LESS_TERMCAP_md=$'\e[1;34m'
export LESS_TERMCAP_so=$'\e[1;33;44m'
export LESS_TERMCAP_us=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'

if [[ -f $HOME/.local/bin ]]; then
    mkdir -p "$HOME/.local/bin"
fi

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME/.local/bin:$HOME/.cargo/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.local/share/gem/ruby/3.4.0/bin:$PATH"

autoload -Uz compinit
compinit -C

bindkey -v
export KEYTIMEOUT=1

## remove it if your there files in completion
# if [ -d ".zsh/completion" ]; then
#    source $HOME/.zsh/completion/* 2>/dev/null
# fi

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# if [[ -f /usr/bin/eza ]]; then
#    alias ls='eza --color=always'
# else
    alias ls='ls --color=always'
# fi

# if [ -f /usr/bin/grep ]; then
#     alias grep='grep --color'
# fi

# if [[ -n z ]]; then
#     alias cd='z' # just use cd -w-
# fi

alias ..="cd .."
alias ...="cd ../.."
